# Generated by Django 2.1.7 on 2023-04-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_employer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Recruiter',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
